#!/usr/bin/perl -WT
#
#   WakeUpManager suite
#
#   Copyright (C) 2008-2009 Maximilian Wilhelm <max@rfc2324.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# The WakeUpManager Agent
#

use strict;
use Carp;

use WakeUpManager::Agent::Daemon;

use Frontier::Daemon 1.01;

my $daemon_port = 2342;

#
# Fire up Agent
my $agent = WakeUpManager::Agent::Daemon->new (configfile => "/etc/wum/agent.conf", verbose => 1);


#
# Create RPC server using transport HTTP on port $daemon_port
# allowing requests only from IPs in allowed_clients list
# dispatching request using methods specified int $agent_wrapper
my $rpc_server = Frontier::Daemon::->new (
	LocalPort => $daemon_port,
	allowed_clients => $agent->get_allowed_clients (),
	methods => $agent->get_methods (),
	syslog => {
		name => "wakeup-agent",
		prefix => "[RPC] ",
		facility => "daemon",
		log_level => "info",
		log_request_path => 0,
	},
	handle_perl_objects => 1,

	no_autolisten => 1,
);

#
# Start listening for request
$rpc_server->listen ();
