#!/usr/bin/perl -WT
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Wed, 04 Jun 2008 15:24:01 +0200
#

our $VERSION = '0.1';

use strict;
use Carp;

use WakeUpManager::Agent::Connector;
use WakeUpManager::Common::Logging;
use WakeUpManager::Config;
use WakeUpManager::DB::HostDB;



my $config_file = "/etc/wum/wum.conf";
my $time_window = '00:15';

log_init ("wakeup-cron", "daemon");

################################################################################
#				Setup stuff				       #
################################################################################

# WakeUpManager::Config will 'confess' on error...
my $config = WakeUpManager::Config->new (config_file => $config_file);

# Get DB handle for 'HostDB'
my $dbi_param = $config->get_dbi_param ('HostDB');
if (! $dbi_param) {
	log_and_die ("Could not get HostDB dbi_param from config file \"$config_file\".\n");
}
my $db_h = WakeUpManager::DB::HostDB->new (dbi_param => $dbi_param);
if (! $db_h) {
	log_and_die ("Failed to get connection to HostDB\n");
}

my $agent_connector = WakeUpManager::Agent::Connector->new (host_db_h => $db_h);
if (! $agent_connector) {
	log_and_die ("Failed to start Agent::Connector\n");
}

my $host_list;
my $host_count;
my $success_count;

################################################################################
#			Boot hosts by host config sets			       #
################################################################################

$host_list = $db_h->get_hosts_to_start_within_next_window ($time_window);
if (! $host_list) {
	log_and_die ("Error: Didn't get hostlist for boot (host config sets).\n");
}

$host_count = scalar (@{$host_list});
$success_count = 0;
if ($host_count > 0 ) {
	log_msg ("info", "Booting hosts according to host config sets...\n");
	foreach my $host_data (@{$host_list}) {
		my $log_msg = "Booting host $host_data->[1] (#$host_data->[0]): ";
		if ($agent_connector->boot_host ($host_data->[0])) {
			$log_msg .= "succeeded.";
			$success_count++;
		} else {
			$log_msg .= "FAILED!";
		}

		log_msg ("info", "$log_msg\n");
	}

	log_msg ("info", "$success_count / $host_count hosts successfully booted.\n");
} else {
	log_msg ("info", "Booting hosts according to host config sets... No hosts to boot.\n");
}



################################################################################
#			Boot hosts by admin config sets			       #
################################################################################

$host_list = $db_h->get_hosts_to_start_within_next_window_admin ($time_window);
if (! $host_list) {
	log_and_die ("Error: Didn't get hostlist for boot (admin config sets).\n");
}

$host_count = scalar (@{$host_list});
$success_count = 0;
if ($host_list > 0 ) {
	log_msg ("info", "Booting hosts according to admin config sets...\n");
	foreach my $host_data (@{$host_list}) {
		my $log_msg = "Booting host $host_data->[1] (#$host_data->[0]): ";
		if ($agent_connector->boot_host ($host_data->[0])) {
			$log_msg .= "succeeded.";
			$success_count++;
		} else {
			$log_msg .= "FAILED!";
		}

		log_msg ("info", "$log_msg\n");
	}

	log_msg ("info", "$success_count / $host_count hosts successfully booted.\n");
} else {
	log_msg ("info", "Booting hosts according to admin config sets... No hosts to boot.\n");
}


# vim:foldmethod=marker
