#!/usr/bin/perl -WT
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Fri May 30 05:05:32 2008
#

use strict;

use WakeUpManager::Common::Utils qw(:timetable);
use WakeUpManager::Config;
use WakeUpManager::DB::HostDB;
use WakeUpManager::WWW::GraphLib;
use WakeUpManager::WWW;


#
# WWW framework
my $www = WakeUpManager::WWW->new (contentless_mode => 1);
if (! $www) {
	print "Content-Type: text/html\n\nAn internal error occured. Please contact the system administrator\n";
}
my $params = $www->{params};

# Get host_id
my $host_id = $params->get_http_param ('host_id');
if (! $host_id) {
	print "<span class=\"error\">Error: No host_id given.</span>\n";
	print STDERR "Called without 'host_id'.\n";
	exit 1;
}

# Try to get users preference for timetable
my $orientation = $params->get_cookie ('timetable_orientation');
if (! defined $orientation || ($orientation ne 'horizontal' && $orientation ne 'vertical')) {
	$orientation = 'horizonal';
}

my $user = $www->{params}->get_user ();
my $lang = $www->{params}->get_lang ();

#
# DB connection
my $wum_config = WakeUpManager::Config->new (config_file => "/etc/wum/wum.conf");
my $host_db = WakeUpManager::DB::HostDB->new (dbi_param => $wum_config->get_dbi_param ("HostDB"));
if (! $host_db) {
        print "<span class=\"error\">Error: No database connection.</span>\n";
	print STDERR "Error: No database connection.\n";
}

my $gl = WakeUpManager::WWW::GraphLib->new ();


#
# Validate input
if (! $host_db->is_valid_host ($host_id)) {
	print "<span class=\"error\">Given host_id is not valid.</span>";
	exit 0;
}

my $host_name = $host_db->get_host_name ($host_id);
if (! $host_name) {
	$host_name = "#$host_id";
}

#
# Check if user is allow to show host config
if (! $host_db->user_can_read_host_config ($user, $host_id)) {
	if ($lang eq 'de') {
		print "Zeitplan f&uuml;r Rechner <i>$host_name</i> kann nicht angezeigt werden: Keine Berechtignung f&uuml;r \"$user\".";
	} else {
		print "<span class=\"error\">Sorry, user \"$user\" is not allowed to view config for host \"$host_name\".</span>";
	}
	exit 0;
}

#
# Query DB for boot times
my $boot_times = $host_db->get_times_of_host ($host_id);
if (! $boot_times) {
	print "<span class=\"error\">Internal error. Please contact your system administrator.</span>";
	exit 0;
}

if (ref ($boot_times) ne 'HASH') {
	print "<span class=\"error\">Internal error. Please contact your system administrator.</span>";
	exit 1;
}

if (! keys %{$boot_times}) {
	if ($lang eq 'de') {
		print "F&uuml;r den Rechner <i>$host_name</i> ist kein Zeitplan definiert.";
	} else {
		print "There is no timetable defined for host <i>$host_name</i>.<br>Maybe you want to contact your system adminstrator";
	}
	exit 0;
}

my $times_list = WakeUpManager::Common::Utils::get_times_list ($boot_times);

print "<img src=\"/ui/ajax/get_time_table_for_host_png?host_id=$host_id\" alt=\"\" usemap=\"#timetable\">\n";

if ($orientation eq 'vertical') {
	print $gl->get_timetable_vertical_map ($times_list, $host_id);
} else {
	print $gl->get_timetable_horizontal_map ($times_list, $host_id);
}
