#!/usr/bin/perl -WT
#
#   WakeUpManager suite
#
#   Copyright (C) 2008-2009 Maximilian Wilhelm <max@rfc2324.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Fri May 30 05:05:32 2008
#

use strict;

use WakeUpManager::Config;
use WakeUpManager::DB::HostDB;
use WakeUpManager::WWW;
use WakeUpManager::WWW::Utils;

#
# WWW lib
my $www = WakeUpManager::WWW->new (contentless_mode => 1);
if (! $www) {
	print "Content-Type: text/html\n\nAn internal error occured. Please contact your system administrator.\n";
}
my $params = $www->{params};

my $hg_id = $params->get_http_param ('hg_id');
my $right = $params->get_http_param ('right');
my $user = $www->{params}->get_auth_info ()->{user};
my $lang = $www->{params}->get_lang ();

if (! $hg_id || ! $right) {
	print "<span class=\"error\">No 'hg_id' or no 'right' parameter given.</span>\n";
	exit 0;
}

#
# DB connection
my $wum_config = WakeUpManager::Config->new (config_file => "/etc/wum/wum.conf");
my $host_db = WakeUpManager::DB::HostDB->new (dbi_param => $wum_config->get_dbi_param ("HostDB"));
if (! $host_db) {
	print "<span class=\"error\">No connection to database. Please contact your system administrator</span>\n";
	exit 0;
}

my $hosts;
my $hg_name;

if ($hg_id eq 'ALL') {
	$hg_name = 'ALL';
	$hosts = $host_db->_hosts_user_has_right_on ($user, $right);
} else {
	$hg_name = $host_db->get_hostgroup_name ($hg_id) || "#$hg_id";
	$hosts = $host_db->_hosts_of_hostgroup_user_has_right_on ($hg_id, $user, $right);
}

if (keys %{$hosts} > 0) {
	print "<select name='host_id'>\n";

	my $hosts_list = WakeUpManager::WWW::Utils->gen_pretty_host_select ($hosts);
	foreach my $item (@{$hosts_list}) {
		print " <option value='$item->{key}'>$item->{val}</option>\n";
	}

	print "</select>\n";
} else {
	if ($lang eq 'de') {
		print "Es sind keine Rechner in der Gruppe <i>$hg_name</i> bekannt oder sie haben nicht die ben&ouml;tigten Rechte.\n";
	} else {
		print "There are no hosts in group <i>$hg_name</i> or you are not allowed to do the requested action to them.\n";
	}
}
