#!/usr/bin/perl -WT
#
#   WakeUpManager suite
#
#   Copyright (C) 2008-2009 Maximilian Wilhelm <max@rfc2324.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Fri May 30 05:05:32 2008
#

use strict;

use WakeUpManager::Common::Utils qw(:timetable);
use WakeUpManager::Config;
use WakeUpManager::DB::HostDB;
use WakeUpManager::WWW;
use WakeUpManager::WWW::GraphLib;

#
# WWW framework
my $www = WakeUpManager::WWW->new (contentless_mode => 1);
if (! $www) {
	print "Content-Type: text/html\n\nAn internal error occured. Please contact the system administrator\n";
}
my $params = $www->{params};

# Get host_id
my $host_id = $params->get_http_param ("host_id");
if (! $host_id) {
	print "<span class=\"error\">Error: No host_id given.</span>\n";
	print STDERR "Called without 'host_id'.\n";
	exit 1;
}

# Try to get users preference for timetable
my $orientation = $params->get_cookie('timetable_orientation');
if (! defined $orientation || ($orientation ne 'horizontal' && $orientation ne 'vertical')) {
	$orientation = 'horizontal';
}

#
# DB connection
my $wum_config = WakeUpManager::Config->new (config_file => "/etc/wum/wum.conf");
my $host_db = WakeUpManager::DB::HostDB->new (dbi_param => $wum_config->get_dbi_param ("HostDB"));

if (! $host_db) {
        print "<span class=\"error\">Error: No database connection.</span>\n";
	print STDERR "Error: No database connection.\n";
}

my $gl = WakeUpManager::WWW::GraphLib->new ();

my $user = $params->get_auth_info()->{user};

#
# (Input) validation made easy, as we have to return an image
# and it's therefore not that simple to push out useful error
# message to the user.
# Nearby the script calling us shouldn't call us in case of
# a detected error.

#
# Validate input
if (! $host_db->is_valid_host ($host_id)) {
	exit 0;
}

#
# Check if user is allow to show host config
if (! $host_db->user_can_read_host_config ($user, $host_id)) {
	exit 0;
}

#
# Query DB for boot times
my $boot_times = $host_db->get_times_of_host ($host_id);
if (! $boot_times) {
	exit 0;
}

if (ref ($boot_times) ne 'HASH') {
	exit 1;
}

#if (! keys %{$boot_times}) {
#	exit 0;
#}

my $times_list = WakeUpManager::Common::Utils::get_times_list ($boot_times);

# Explicit check for 'vertical' and use horizontal as default for no or carppy input
if ($orientation eq 'vertical') {
	$gl->print_timetable_vertical_png ($times_list);
} else {
	$gl->print_timetable_horizontal_png ($times_list);
}
