#!/usr/bin/perl -WT
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Fri May 30 05:05:32 2008
#

use strict;

use WakeUpManager::Config;
use WakeUpManager::DB::HostDB;
use WakeUpManager::WWW;


#
# WWW lib
my $www = WakeUpManager::WWW->new (contentless_mode => 1);
if (! $www) {
	print "Content-Type: text/html\n\nAn internal error occured. Please contac the system administrator.\n";
}
my $params = $www->{params};


# Get host_id
my $host_id = $params->get_http_param ('host_id');
if (! $host_id) {
	print "<span class=\"error\">Error: No host_id given.</span>\n";
	print STDERR "Called without 'host_id'.\n";
	exit 1;
}

# Get host_state
my $args = {};
foreach my $arg (qw(boot_host shutdown_host)) {
	my $arg_val = $params->get_http_param ($arg);
	if (! $arg_val) {
		print "<span class=\"error\">Error: No value for \"$arg\" given.</span>\n";
		print STDERR "No value for \"$arg\" given.\n";
		exit 1;
	}

	$args->{$arg} = ($arg_val eq 'true') ? 1 : 0;
}

my $user = $www->{params}->get_auth_info ()->{user};
my $lang = $www->{params}->get_lang ();

#
# DB connection
my $wum_config = WakeUpManager::Config->new (config_file => "/etc/wum/wum.conf");
my $host_db = WakeUpManager::DB::HostDB->new (dbi_param => $wum_config->get_dbi_param ("HostDB"));
if (! $host_db) {
        print "<span class=\"error\">Error: No database connection.</span>\n";
	print STDERR "Error: No database connection.\n";
}

#
# Validate input
if (! $host_db->is_valid_host ($host_id)) {
	print "<span class=\"error\">Given host_id is not valid.</span>";
	exit 0;
}

my $host_name = $host_db->get_host_name ($host_id);
if (! $host_name) {
	$host_name = "#$host_id";
}

#
# Check if user is allow to show host config
if (! $host_db->user_can_write_host_config ($user, $host_id)) {
	print "<span class=\"error\">Sorry, user \"$user\" is not allowed to update config for host \"$host_name\".</span>";
	exit 0;
}


if (! $host_db->set_host_state ($host_id, $args->{boot_host}, $args->{shutdown_host})) {
	print "<span class=\"error\">Error while setting host state.</span>\n";
	exit 1;
}

if ($lang eq 'de') {
	print "Status wurde gespeichert.\n";
} else {
	print "Host state has been saved.\n";
}
