#!/usr/bin/perl -WT
#
# Maximilian Wilhelm <max@rfc2324.org>
#  --  Fri May 30 05:05:32 2008
#

use strict;

use WakeUpManager::WWW;


#
# WWW lib
my $www = WakeUpManager::WWW->new (
	ajax_mode => 1,
	ajax_page_name => 'HostState',
	ajax_func_name => 'set_host_state',
);
if (! $www) {
	print "Content-Type: text/html\n\nAn internal error occured. Please contac the system administrator.\n";
}

print $www->get_page ();
